In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_zeros = torch.rand_like(x_data, dtype=torch.float)
print(f"Zeros Tensor: \n {x_zeros} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zeros Tensor: 
 tensor([[0.2626, 0.3095],
        [0.6991, 0.3097]]) 



In [10]:
# with random or constant values
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Random Tensor: \n {ones_tensor} \n")
print(f"Random Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4063, 0.4509, 0.1126],
        [0.1534, 0.5491, 0.1776]]) 

Random Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [12]:
# attributes of a tensor
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


In [16]:
# operations in tensors

# slicing and indexing
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[: ,1]}")
print(f"Last column: {tensor[..., -1]}")

tensor[:, 2] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [26]:
# Joining tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.],
        [1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1.]])

In [30]:
t2 = torch.stack([tensor, tensor, tensor], dim=1)
t2

tensor([[[1., 1., 0., 1.],
         [1., 1., 0., 1.],
         [1., 1., 0., 1.]],

        [[1., 1., 0., 1.],
         [1., 1., 0., 1.],
         [1., 1., 0., 1.]],

        [[1., 1., 0., 1.],
         [1., 1., 0., 1.],
         [1., 1., 0., 1.]],

        [[1., 1., 0., 1.],
         [1., 1., 0., 1.],
         [1., 1., 0., 1.]]])

In [35]:
# identity matrix
ti = torch.eye(n=4)
ti

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [37]:
y1 = tensor @ ti
y1

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])

In [38]:
y1 = tensor.matmul(ti)
y1

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])

In [40]:
tensor * tensor

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])

In [41]:
tensor @ tensor

tensor([[3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [3., 3., 0., 3.],
        [3., 3., 0., 3.]])